[smtp]
host = "smtp.gmail.com"
port = 465
use_ssl = true
user = "sean.chinery@gmail.com"
password = "efnc jrtv vxwj cczn"  # no spaces
from = "sean.chinery@gmail.com"                   # MUST equal user for Gmail
force_from_user = true
to = "sean.chinery@atlantichealth.org"
