[smtp]
host = "smtp.gmail.com"        # or your company SMTP
port = 465                     # 465=SSL, 587=STARTTLS
user = "you@example.com"
password = "APP_PASSWORD_OR_TOKEN"
from = "Supply Bot <you@example.com>"
to = "team@example.com,manager@example.com"
