[smtp]
host = "smtp.gmail.com"
port = 465
use_ssl = true
user = "sean.chinery@gmail.com"          # the Gmail address you log in with
password = "kzbyzcqywcjerfpe" # no spaces
from = "sean.chinery@gmail.com"          # must match user when using Gmail
force_from_user = true
to = "sean.chinery@atlantichealth.org"
