[smtp]
host = "smtp.gmail.com"
port = 587    # SSL
use_ssl = true
user = "sean.chinery@gmail.com"
password = "rsdtnzwsohofntho"   # 16-char app password
from = "sean.chinery@gmail.com"      # or "Supply Bot <you@yourdomain.com>"
force_from_user = true
to = "sean.chinery@atlantichealth.org"
