[smtp]
host = "smtp.gmail.com"
port = 465
use_ssl = true                 # SSL on 465
user = "sean.chinery@gmail.com"
password = "ldmdkyocuwckdkhi"   # paste exactly, no spaces
from = "Supply Bot <sean.chinery@gmail.com>"  # display name is fine
force_from_user = true         # ensures From == user for Gmail
to = "sean.chinery@atlantichealth.org"
