[smtp]
host = "smtp.gmail.com"        # or your company SMTP, e.g. "smtp.office365.com"
port = 465                     # 465 (SSL) or 587 (STARTTLS)
user = "sean.chinery@gmail.com"       # optional if your SMTP allows unauthenticated send
password = "vylt apkg jjkr swrx" # for Gmail/365 use an App Password
from = "Supply Bot <sean.chinery@atlantichealth.org>"
to = "sean.chinery@atlantichealth.org"    # optional default; you can edit in the UI
